# Generated by Django 6.0.1 on 2026-01-13 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcartCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de création de l'écart")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('commande_asten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='asten.commandeasten', verbose_name='Commande Asten')),
            ],
            options={
                'verbose_name': 'Écart de commande',
                'verbose_name_plural': 'Écarts de commandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
