# Generated by Django 6.0.1 on 2026-01-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0002_ecartgpv'),
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcartLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de création de l'écart")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('type_ecart', models.CharField(choices=[('gpv_absent', 'Absent dans GPV'), ('cyrus_absent', 'Absent dans Cyrus'), ('coherence', 'Écart de cohérence globale')], default='gpv_absent', max_length=20, verbose_name="Type d'écart")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('commande_legend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='legend.commandelegend', verbose_name='Commande Legend')),
            ],
            options={
                'verbose_name': 'Écart de commande Legend',
                'verbose_name_plural': 'Écarts de commandes Legend',
                'ordering': ['-date_creation'],
            },
        ),
    ]











