# Generated by Django 6.0.1 on 2026-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0005_remove_ecartbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecartcommande',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ignore', 'Ignoré'), ('quantite_0', 'Quantité 0')], default='ouvert', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ecartgpv',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ignore', 'Ignoré'), ('quantite_0', 'Quantité 0')], default='ouvert', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ecartlegend',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ignore', 'Ignoré'), ('quantite_0', 'Quantité 0')], default='ouvert', max_length=20, verbose_name='Statut'),
        ),
    ]
