# Generated by Django 6.0.1 on 2026-08-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('facture_cyrus', 'Factures Cyrus (lignes)'), ('facture_asten', 'Factures Asten (lignes)'), ('facture_ecart_statut', 'Statuts factures en écart'), ('br_ic', 'BR IC (lignes)'), ('br_asten', 'BR Asten'), ('br_anomalie', 'BR anomalies'), ('entree_journal', 'Journal POS (entrées)')], max_length=40, verbose_name='Source')),
                ('mois', models.DateField(help_text='Premier jour du mois concerné', verbose_name='Mois')),
                ('nb_lignes', models.BigIntegerField(default=0, verbose_name='Lignes supprimées')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Résumé détaillé')),
                ('archive_le', models.DateTimeField(auto_now_add=True, verbose_name='Archivé le')),
            ],
            options={
                'verbose_name': 'Archive mensuelle',
                'verbose_name_plural': 'Archives mensuelles',
                'ordering': ['-mois', 'source'],
                'unique_together': {('source', 'mois')},
            },
        ),
    ]
