# Generated by Django 6.0.1 on 2026-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierPurge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('facture_cyrus', 'Factures Cyrus (CSV)'), ('facture_asten', 'Factures Asten (CSV)'), ('br_anomalie', 'Anomalies BR (CSV)')], max_length=20, verbose_name='Type de fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('nb_lignes', models.BigIntegerField(default=0, verbose_name='Lignes purgées')),
                ('purge_le', models.DateTimeField(auto_now_add=True, verbose_name='Purgé le')),
            ],
            options={
                'verbose_name': 'Fichier purgé',
                'verbose_name_plural': 'Fichiers purgés',
                'ordering': ['-purge_le'],
                'unique_together': {('type_fichier', 'nom_fichier')},
            },
        ),
    ]
