"""
Django settings for verification_commande project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger le fichier config.env à la racine du projet si il existe
config_file = BASE_DIR / 'config.env'
if config_file.exists():
    from decouple import Config, RepositoryEnv
    config = Config(RepositoryEnv(str(config_file)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='yz#z7*wk(1isj_m(emr4im=tp^!q2pva6=!xx4&0^t6u7m$2nu')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['10.10.9.1', 'localhost', '127.0.0.1', '10.0.70.27', 'proserv-suivi.lan']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'imports',
    'asten',
    'cyrus',
    'gpv',
    'legend',
    'br',
    'ecarts',
    'dashboard',
    'tickets',
    'entree_journal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'core.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'verification_commande.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.ecarts_notification',
            ],
        },
    },
]

WSGI_APPLICATION = 'verification_commande.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / '.cache',
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default='traitement_n8n'),
        'USER': config('POSTGRES_USER', default='postgres'),
        'PASSWORD': config('POSTGRES_PASSWORD', default=''),
        'HOST': config('POSTGRES_HOST', default='localhost'),
        'PORT': config('POSTGRES_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Authentification
AUTHENTICATION_BACKENDS = [
    'core.backends.CaseInsensitiveBackend',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Session
SESSION_COOKIE_AGE = 86400 * 7   # 7 jours
SESSION_SAVE_EVERY_REQUEST = True  # évite les sessions périmées
SESSION_COOKIE_HTTPONLY = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / config('MEDIA_ROOT', default='media')

# Configuration des chemins des dossiers d'import
# Les chemins peuvent être relatifs à MEDIA_ROOT ou absolus
DOSSIER_COMMANDES_ASTEN = config('DOSSIER_COMMANDES_ASTEN', default='commande_asten')
DOSSIER_COMMANDES_CYRUS = config('DOSSIER_COMMANDES_CYRUS', default='commande_cyrus')
DOSSIER_COMMANDES_GPV = config('DOSSIER_COMMANDES_GPV', default='commande_gpv')
DOSSIER_COMMANDES_LEGEND = config('DOSSIER_COMMANDES_LEGEND', default='commande_legend')
DOSSIER_BR_ASTEN = config('DOSSIER_BR_ASTEN', default='br_asten')
DOSSIER_BR_IC = config('DOSSIER_BR_IC', default='br_ic')
DOSSIER_ANOMALIE_BR = config('DOSSIER_ANOMALIE_BR', default='anomalie_br')
# Factures Backup (Facture Cyrus)
DOSSIER_FACTURE_BACKUP = config('DOSSIER_FACTURE_BACKUP', default='facture_backup')
# Factures Sage (fichiers CSV)
DOSSIER_FACTURES_SAGE = config('DOSSIER_FACTURES_SAGE', default='smb://10.0.70.150/automate-ic/ARCHIVES')
FACTURES_SAGE_PREFIX = config('FACTURES_SAGE_PREFIX', default='SAGE-I-SP_')

def get_dossier_path(dossier_config):
    """
    Retourne le chemin absolu du dossier.
    Si le chemin est absolu (commence par / ou // pour UNC), il est utilisé tel quel.
    Sinon, il est relatif à MEDIA_ROOT.
    """
    dossier_config_str = str(dossier_config).strip()
    
    # Détecter les chemins smb:// et convertir en format UNC (//serveur/partage)
    if dossier_config_str.lower().startswith('smb://'):
        dossier_config_str = '//' + dossier_config_str[6:]

    # Détecter les chemins UNC (réseau Windows/Samba) qui commencent par // ou \\
    if dossier_config_str.startswith('//') or dossier_config_str.startswith('\\\\'):
        # Chemin réseau UNC - utiliser tel quel
        return Path(dossier_config_str)
    
    # Détecter les chemins absolus Unix/Linux (commencent par /)
    if dossier_config_str.startswith('/'):
        return Path(dossier_config_str)
    
    # Sinon, chemin relatif à MEDIA_ROOT
    return Path(MEDIA_ROOT) / dossier_config_str

# Chemins absolus des dossiers
DOSSIER_COMMANDES_ASTEN_PATH = get_dossier_path(DOSSIER_COMMANDES_ASTEN)
DOSSIER_COMMANDES_CYRUS_PATH = get_dossier_path(DOSSIER_COMMANDES_CYRUS)
DOSSIER_COMMANDES_GPV_PATH = get_dossier_path(DOSSIER_COMMANDES_GPV)
DOSSIER_COMMANDES_LEGEND_PATH = get_dossier_path(DOSSIER_COMMANDES_LEGEND)
DOSSIER_BR_ASTEN_PATH = get_dossier_path(DOSSIER_BR_ASTEN)
DOSSIER_BR_IC_PATH = get_dossier_path(DOSSIER_BR_IC)
DOSSIER_ANOMALIE_BR_PATH = get_dossier_path(DOSSIER_ANOMALIE_BR)
DOSSIER_FACTURE_BACKUP_PATH = get_dossier_path(DOSSIER_FACTURE_BACKUP)
DOSSIER_FACTURES_SAGE_PATH = get_dossier_path(DOSSIER_FACTURES_SAGE)
DOSSIER_VERSIONS_ASTEN = config('DOSSIER_VERSIONS_ASTEN', default='/mnt/asten/Cegid/AstenProd/ReferentielPrecom/Backup')
DOSSIER_VERSIONS_ASTEN_PATH = get_dossier_path(DOSSIER_VERSIONS_ASTEN)
# Factures Cyrus / Asten (CSV bruts pour vérification)
DOSSIER_FACTURES_CYRUS = config('DOSSIER_FACTURES_CYRUS', default='facture_cyrus')
DOSSIER_FACTURES_ASTEN_CSV = config('DOSSIER_FACTURES_ASTEN', default='facture_asten')
DOSSIER_FACTURES_CYRUS_PATH = get_dossier_path(DOSSIER_FACTURES_CYRUS)
DOSSIER_FACTURES_ASTEN_CSV_PATH = get_dossier_path(DOSSIER_FACTURES_ASTEN_CSV)

CSRF_TRUSTED_ORIGINS = ['http://10.0.70.27:1212', 'http://proserv-suivi.lan', 'http://proserv-suivi.lan:1212']

# Assistant IA — fournisseur configurable (gemini / nvidia)
AI_PROVIDER = config('AI_PROVIDER', default='gemini')

# Gemini AI
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL_DEFAULT', default='gemini-2.5-flash')

# NVIDIA NIM (API compatible OpenAI — https://build.nvidia.com)
# mixtral-8x7b-instruct : meilleur compromis vitesse/fiabilité observé (~11-20s,
# JSON valide de façon consistante avec le prompt durci). llama-3.1-70b est plus
# précis mais prend 20-40s (cause des timeouts) ; llama-3.1-8b est plus rapide
# mais génère du JSON mal formé de façon inconsistante.
NVIDIA_API_KEY = config('NVIDIA_API_KEY', default='')
NVIDIA_MODEL = config('NVIDIA_MODEL_DEFAULT', default='mistralai/mixtral-8x7b-instruct-v0.1')
