"""
Django settings for verification_commande project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger le fichier config.env à la racine du projet si il existe
config_file = BASE_DIR / 'config.env'
if config_file.exists():
    from decouple import Config, RepositoryEnv
    config = Config(RepositoryEnv(str(config_file)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#b64ydqegmz%*=qb%w_mw5ynh!k^=yiqd38xte&0&f%6gwu)n*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.10.9.1', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'imports',
    'asten',
    'cyrus',
    'gpv',
    'legend',
    'br',
    'ecarts',
    'dashboard',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'verification_commande.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'verification_commande.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / config('MEDIA_ROOT', default='media')

# Configuration des chemins des dossiers d'import
# Les chemins peuvent être relatifs à MEDIA_ROOT ou absolus
DOSSIER_COMMANDES_ASTEN = config('DOSSIER_COMMANDES_ASTEN', default='commande_asten')
DOSSIER_COMMANDES_CYRUS = config('DOSSIER_COMMANDES_CYRUS', default='commande_cyrus')
DOSSIER_COMMANDES_GPV = config('DOSSIER_COMMANDES_GPV', default='commande_gpv')
DOSSIER_COMMANDES_LEGEND = config('DOSSIER_COMMANDES_LEGEND', default='commande_legend')
DOSSIER_BR_ASTEN = config('DOSSIER_BR_ASTEN', default='br_asten')

def get_dossier_path(dossier_config):
    """
    Retourne le chemin absolu du dossier.
    Si le chemin est absolu (commence par / ou // pour UNC), il est utilisé tel quel.
    Sinon, il est relatif à MEDIA_ROOT.
    """
    dossier_config_str = str(dossier_config).strip()
    
    # Détecter les chemins UNC (réseau Windows/Samba) qui commencent par // ou \\
    if dossier_config_str.startswith('//') or dossier_config_str.startswith('\\\\'):
        # Chemin réseau UNC - utiliser tel quel
        return Path(dossier_config_str)
    
    # Détecter les chemins absolus Unix/Linux (commencent par /)
    if dossier_config_str.startswith('/'):
        return Path(dossier_config_str)
    
    # Sinon, chemin relatif à MEDIA_ROOT
    return Path(MEDIA_ROOT) / dossier_config_str

# Chemins absolus des dossiers
DOSSIER_COMMANDES_ASTEN_PATH = get_dossier_path(DOSSIER_COMMANDES_ASTEN)
DOSSIER_COMMANDES_CYRUS_PATH = get_dossier_path(DOSSIER_COMMANDES_CYRUS)
DOSSIER_COMMANDES_GPV_PATH = get_dossier_path(DOSSIER_COMMANDES_GPV)
DOSSIER_COMMANDES_LEGEND_PATH = get_dossier_path(DOSSIER_COMMANDES_LEGEND)
DOSSIER_BR_ASTEN_PATH = get_dossier_path(DOSSIER_BR_ASTEN)
