# Generated by Django 6.0.1 on 2026-04-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeasten',
            name='cree_par',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='commandeasten',
            name='date_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AddField(
            model_name='commandeasten',
            name='date_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='commandeasten',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='commandeasten',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence externe'),
        ),
        migrations.AddField(
            model_name='commandeasten',
            name='validee_par',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Validée par'),
        ),
    ]
