# Generated by Django 6.0.1 on 2026-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asten', '0002_add_validation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeasten',
            name='heure_validation',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de validation'),
        ),
    ]
