#!/bin/bash
echo "=========================================="
echo "📍 CHEMINS CONFIGURÉS"
echo "=========================================="
echo ""
echo "📁 Fichiers AUTO :"
echo "   /home/youssef/Documents/traitement_n8n/traitement/export1/"
echo ""
echo "📁 Fichiers MANUAL :"
echo "   /home/youssef/Documents/traitement_n8n/extractions/commande_manual/"
echo ""
echo "📁 Archive :"
echo "   /home/youssef/Documents/traitement_n8n/extractions/archive/"
echo ""
echo "=========================================="
echo "📊 FICHIERS ACTUELLEMENT PRÉSENTS"
echo "=========================================="
echo ""
echo "Fichiers AUTO :"
ls -lh traitement/export1/ 2>/dev/null | tail -n +2 || echo "   (aucun fichier)"
echo ""
echo "Fichiers MANUAL :"
ls -lh extractions/commande_manual/ 2>/dev/null | tail -n +2 || echo "   (aucun fichier)"
