# Generated by Django 6.0.1 on 2026-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code magasin')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du magasin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['code'],
            },
        ),
    ]
