# Generated by Django 6.0.1 on 2026-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.apppermission'),
        ),
    ]
