# Generated by Django 6.0.1 on 2026-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='full_asten',
            field=models.BooleanField(default=False, verbose_name='Full Asten'),
        ),
    ]
