# Generated by Django 6.0.1 on 2026-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_full_asten_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='exclure_factures',
            field=models.BooleanField(default=False, verbose_name='Exclure des stats factures'),
        ),
    ]
