# Generated by Django 6.0.1 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_magasin_exclure_factures'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='magasin_asten',
            field=models.BooleanField(default=False, verbose_name='Magasin Asten (passe commande Asten)'),
        ),
    ]
