# Generated by Django 6.0.1 on 2026-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_magasin_magasin_asten'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='magasin_br',
            field=models.BooleanField(default=True, verbose_name='Magasin BR (suivi des bons de réception)'),
        ),
    ]
