# Generated by Django 6.0.1 on 2026-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('asten', 'Asten'), ('cyrus', 'Cyrus')], max_length=10, verbose_name='Type de fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('chemin_fichier', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('nombre_lignes', models.IntegerField(default=0, verbose_name='Nombre de lignes importées')),
                ('nombre_nouveaux', models.IntegerField(default=0, verbose_name='Nombre de nouvelles commandes')),
                ('nombre_dupliques', models.IntegerField(default=0, verbose_name='Nombre de doublons ignorés')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Import de fichier',
                'verbose_name_plural': 'Imports de fichiers',
                'ordering': ['-date_import'],
            },
        ),
    ]
