# Generated by Django 6.0.1 on 2026-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_facture_sage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfichier',
            name='type_fichier',
            field=models.CharField(choices=[('asten', 'Asten'), ('cyrus', 'Cyrus'), ('gpv', 'GPV'), ('legend', 'Legend'), ('br_asten', 'BR Asten')], max_length=10, verbose_name='Type de fichier'),
        ),
    ]
