# Generated by Django 6.0.1 on 2026-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_importfichier_type_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureAstenBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('chemin_fichier', models.CharField(max_length=500, unique=True, verbose_name='Chemin du fichier')),
                ('code_magasin', models.CharField(max_length=10, verbose_name='Code magasin')),
                ('date_facture', models.DateField(verbose_name='Date facture')),
                ('numero_facture', models.CharField(max_length=20, verbose_name='Numéro facture')),
                ('date_modif', models.DateTimeField(verbose_name='Date de modification')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Facture Asten Backup',
                'verbose_name_plural': 'Factures Asten Backup',
                'ordering': ['-date_facture', '-date_modif', 'nom_fichier'],
            },
        ),
    ]
