# Generated by Django 6.0.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_factureastenbackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureBackupCyrus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_magasin', models.CharField(max_length=3, verbose_name='Code magasin')),
                ('numero_facture', models.CharField(max_length=30, verbose_name='Numéro facture')),
                ('type_facture', models.CharField(choices=[('general', 'Générale'), ('promo', 'Promo')], max_length=10, verbose_name='Type facture')),
                ('theme_promo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Thème promo')),
                ('nom_fichier', models.CharField(max_length=255, unique=True, verbose_name='Nom du fichier')),
                ('chemin_fichier', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('date_modif', models.DateTimeField(verbose_name='Date de modification')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Facture Backup Cyrus',
                'verbose_name_plural': 'Factures Backup Cyrus',
                'ordering': ['-date_modif', 'nom_fichier'],
            },
        ),
    ]




