# Generated by Django 6.0.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_facturebackupcyrus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfichier',
            name='type_fichier',
            field=models.CharField(choices=[('asten', 'Asten'), ('cyrus', 'Cyrus'), ('gpv', 'GPV'), ('legend', 'Legend'), ('br_asten', 'BR Asten'), ('facture_backup', 'Facture Backup')], max_length=20, verbose_name='Type de fichier'),
        ),
    ]




