# Generated by Django 6.0.1 on 2026-03-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_alter_importfichier_type_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortimentVersionSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code assortiment')),
                ('statut', models.CharField(max_length=20, verbose_name='Statut')),
                ('nb_fichiers_presents', models.IntegerField(default=0)),
                ('nb_manquants', models.IntegerField(default=0)),
                ('total_articles', models.IntegerField(default=0)),
                ('fichiers', models.JSONField(default=list, verbose_name='Détail fichiers')),
            ],
            options={
                'verbose_name': 'Assortiment (snap)',
                'verbose_name_plural': 'Assortiments (snaps)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VersionAstenSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom du dossier')),
                ('date', models.DateField(verbose_name='Date de génération')),
                ('heure', models.CharField(max_length=10, verbose_name='Heure')),
                ('statut', models.CharField(max_length=20, verbose_name='Statut global')),
                ('conformite_pct', models.IntegerField(default=0, verbose_name='Conformité %')),
                ('nb_fichiers_total', models.IntegerField(default=0, verbose_name='Nb fichiers total')),
                ('taille_raw', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('taille_fmt', models.CharField(default='', max_length=20, verbose_name='Taille formatée')),
                ('nb_ok', models.IntegerField(default=0, verbose_name='Assortiments OK')),
                ('nb_incomplet', models.IntegerField(default=0, verbose_name='Assortiments incomplets')),
                ('nb_absent', models.IntegerField(default=0, verbose_name='Assortiments absents')),
                ('assortiments_manquants', models.JSONField(default=list, verbose_name='Codes assortiments manquants')),
                ('assortiments_extra', models.JSONField(default=list, verbose_name='Codes assortiments extra')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Dernière sync')),
            ],
            options={
                'verbose_name': 'Version Asten (snap)',
                'verbose_name_plural': 'Versions Asten (snaps)',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.DeleteModel(
            name='FactureAstenBackup',
        ),
        migrations.AddField(
            model_name='assortimentversionsnap',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assortiments', to='imports.versionastensnap'),
        ),
        migrations.AlterUniqueTogether(
            name='assortimentversionsnap',
            unique_together={('version', 'code')},
        ),
    ]
