# Generated by Django 6.0.1 on 2026-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_add_version_asten_snaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureEcartStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_facture', models.CharField(max_length=50, verbose_name='Clé facture')),
                ('dfac_str', models.CharField(max_length=10, verbose_name='Date DFAC (YYMMDD)')),
                ('cidc', models.CharField(max_length=10, verbose_name='Code magasin (CIDC)')),
                ('statut', models.CharField(choices=[('non_integre', 'Non intégré'), ('integre', 'Intégré'), ('ignore', 'Ignoré')], default='non_integre', max_length=15, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Statut facture en écart',
                'verbose_name_plural': 'Statuts factures en écart',
                'ordering': ['-date_modif'],
                'unique_together': {('cle_facture', 'dfac_str', 'cidc')},
            },
        ),
    ]
