# Generated by Django 6.0.1 on 2026-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_add_facture_ecart_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureAstenLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_bon_livraison', models.CharField(db_index=True, max_length=50)),
                ('magasin', models.CharField(db_index=True, max_length=20)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=255)),
                ('statut_commande', models.CharField(blank=True, default='', max_length=100)),
                ('date_reception_str', models.CharField(blank=True, default='', max_length=30)),
                ('date_reception_date', models.DateField(blank=True, null=True)),
                ('quantite_totale', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('valorisation_ht', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('valorisation_ttc', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('type_reception', models.CharField(blank=True, default='', max_length=50)),
                ('fichier', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne facture Asten',
                'indexes': [models.Index(fields=['n_bon_livraison', 'magasin'], name='imports_fac_n_bon_l_a84e74_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactureCyrusLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_facture', models.CharField(db_index=True, max_length=50)),
                ('nsee', models.CharField(max_length=10)),
                ('nfac', models.CharField(max_length=20)),
                ('dfac_str', models.CharField(max_length=10)),
                ('dfac_date', models.DateField(blank=True, null=True)),
                ('cidc', models.CharField(db_index=True, max_length=10)),
                ('lart', models.CharField(blank=True, default='', max_length=255)),
                ('nart', models.CharField(blank=True, default='', max_length=50)),
                ('pvtc', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('ptvc', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('pfth', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('fichier', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne facture Cyrus',
                'indexes': [models.Index(fields=['cle_facture', 'cidc'], name='imports_fac_cle_fac_1085e5_idx')],
            },
        ),
    ]
