# Generated by Django 6.0.1 on 2026-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_facture_cyrus_asten_lignes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecyrusligne',
            name='qlvu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
