# Generated by Django 6.0.1 on 2026-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0011_mv_factures_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfichier',
            name='type_fichier',
            field=models.CharField(choices=[('asten', 'Asten'), ('cyrus', 'Cyrus'), ('gpv', 'GPV'), ('legend', 'Legend'), ('br_asten', 'BR Asten'), ('br_ic', 'BR IC'), ('facture_backup', 'Facture Backup')], max_length=20, verbose_name='Type de fichier'),
        ),
        migrations.AddIndex(
            model_name='factureastenligne',
            index=models.Index(fields=['magasin', 'date_reception_date'], name='imports_fac_magasin_58f8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='factureastenligne',
            index=models.Index(fields=['date_reception_date'], name='imports_fac_date_re_9db5e4_idx'),
        ),
    ]
