# Generated by Django 6.0.1 on 2026-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0013_mv_factures_joined_v2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facturecyrusligne',
            index=models.Index(fields=['dfac_date'], name='imports_fac_dfac_da_08ecaf_idx'),
        ),
        migrations.AddIndex(
            model_name='facturecyrusligne',
            index=models.Index(fields=['cidc', 'dfac_date'], name='imports_fac_cidc_f9f726_idx'),
        ),
    ]
