# Generated by Django 6.0.1 on 2026-01-12 10:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_controle', models.CharField(choices=[('commande', 'Commande'), ('facture', 'Facture'), ('br', 'BR'), ('legend', 'Legend')], max_length=50)),
                ('periode', models.CharField(help_text='Période du contrôle (ex: 2026-01)', max_length=50)),
                ('date_execution', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_lignes', models.IntegerField(default=0)),
                ('total_ecarts', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
            ],
            options={
                'verbose_name': 'Contrôle',
                'verbose_name_plural': 'Contrôles',
                'ordering': ['-date_execution'],
            },
        ),
        migrations.CreateModel(
            name='FichierSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_controle', models.CharField(choices=[('commande', 'Commande'), ('facture', 'Facture'), ('br', 'BR'), ('legend', 'Legend')], max_length=50)),
                ('origine', models.CharField(choices=[('auto', 'Automatique (Source A)'), ('manual', 'Manuel (Source B)')], max_length=20)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin', models.CharField(max_length=500)),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('traite', models.BooleanField(default=False)),
                ('controle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers', to='traitement.controle')),
            ],
            options={
                'verbose_name': 'Fichier source',
                'verbose_name_plural': 'Fichiers sources',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Ecart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Clé de référence pour la comparaison', max_length=255)),
                ('valeur_source_a', models.TextField(blank=True, help_text='Valeur dans la source A', null=True)),
                ('valeur_source_b', models.TextField(blank=True, help_text='Valeur dans la source B', null=True)),
                ('type_ecart', models.CharField(choices=[('absent_a', 'Présent dans B mais absent dans A'), ('absent_b', 'Présent dans A mais absent dans B'), ('valeur_differente', 'Valeurs différentes')], max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, help_text="Détails supplémentaires de l'écart", null=True)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecarts', to='traitement.controle')),
            ],
            options={
                'verbose_name': 'Écart',
                'verbose_name_plural': 'Écarts',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['controle', 'type_ecart'], name='traitement__control_29c4f1_idx'), models.Index(fields=['reference'], name='traitement__referen_d84925_idx')],
            },
        ),
    ]
