# Generated by Django 6.0.1 on 2026-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiersource',
            name='origine',
            field=models.CharField(choices=[('asten', 'Asten (Source A)'), ('cyrus', 'Cyrus (Source B)')], max_length=20),
        ),
    ]
