# Generated by Django 6.0.1 on 2026-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0002_alter_fichiersource_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecart',
            name='type_ecart',
            field=models.CharField(choices=[('absent_a', 'Présent dans B mais absent dans A'), ('absent_b', 'Présent dans A mais absent dans B'), ('valeur_differente', 'Valeurs différentes'), ('corrige', 'Écart corrigé')], max_length=50),
        ),
    ]
