# Generated by Django 6.0.1 on 2026-06-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question type (en français)')),
                ('sql', models.TextField(verbose_name='Requête SQL correcte associée')),
                ('note', models.TextField(blank=True, default='', verbose_name='Explication / piège à éviter')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrée base de connaissance IA',
                'verbose_name_plural': 'Entrées base de connaissance IA',
                'ordering': ['-date_modification'],
            },
        ),
    ]
