# Generated by Django 6.0.1 on 2026-01-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeGPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, verbose_name='Numéro de commande')),
                ('nom_magasin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom magasin')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_transfert', models.DateField(blank=True, null=True, verbose_name='Date de transfert')),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
                ('code_magasin', models.ForeignKey(db_column='code_magasin', on_delete=django.db.models.deletion.PROTECT, to='core.magasin', verbose_name='Code magasin')),
            ],
            options={
                'verbose_name': 'Commande GPV',
                'verbose_name_plural': 'Commandes GPV',
                'ordering': ['-date_creation', 'numero_commande'],
                'indexes': [models.Index(fields=['date_creation', 'numero_commande', 'code_magasin'], name='gpv_command_date_cr_44c3a0_idx'), models.Index(fields=['date_creation'], name='gpv_command_date_cr_4cb719_idx'), models.Index(fields=['code_magasin'], name='gpv_command_code_ma_1c267c_idx')],
                'unique_together': {('date_creation', 'numero_commande', 'code_magasin')},
            },
        ),
    ]
