# Generated by Django 6.0.1 on 2026-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandegpv',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commandegpv',
            name='date_transfert',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de transfert'),
        ),
        migrations.AlterField(
            model_name='commandegpv',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
    ]
