# Generated by Django 6.0.1 on 2026-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichierImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255, unique=True)),
                ('pos_id', models.CharField(max_length=20)),
                ('nb_lignes', models.IntegerField(default=0)),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fichier importé',
                'ordering': ['-importe_le'],
            },
        ),
        migrations.CreateModel(
            name='EntreeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('pos_id', models.CharField(db_index=True, max_length=20)),
                ('pos_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('entry_type_value', models.IntegerField(default=30)),
                ('entry_type_label', models.CharField(max_length=100)),
                ('entry_type_detail_type', models.CharField(db_index=True, max_length=100)),
                ('entry_type_detail_text', models.CharField(max_length=200)),
                ('status_value', models.IntegerField(choices=[(0, 'Erreur'), (1, 'En cours'), (2, 'Succès'), (3, 'Indéfini')], default=2)),
                ('status_label', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('report', models.TextField(blank=True)),
                ('shop_reference', models.CharField(db_index=True, max_length=20)),
                ('shop_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Entrée journal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'shop_reference', 'entry_type_detail_type'], name='entree_jour_created_201258_idx'), models.Index(fields=['pos_id', 'created_at'], name='entree_jour_pos_id_4e6b8a_idx')],
            },
        ),
    ]
