# Generated by Django 6.0.1 on 2026-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree_journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFichierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=100, unique=True, verbose_name='Type')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Label')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (affiché et comptabilisé)')),
            ],
            options={
                'verbose_name': 'Configuration type fichier',
                'ordering': ['type_key'],
            },
        ),
    ]
