# Generated by Django 6.0.1 on 2026-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree_journal', '0002_typefichierconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErreurIgnoreeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, unique=True, verbose_name='Pattern (texte recherché)')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('ignorer', models.BooleanField(default=True, verbose_name='Ignorer (traiter comme avertissement, pas comme erreur)')),
            ],
            options={
                'verbose_name': 'Configuration erreur ignorée',
                'ordering': ['pattern'],
            },
        ),
    ]
