# Generated by Django 6.0.1 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CommandeLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_brut', models.CharField(max_length=100, verbose_name='Numéro brut')),
                ('numero_commande', models.CharField(max_length=50, verbose_name='Numéro de commande')),
                ('depot_origine', models.CharField(max_length=100, verbose_name="Dépôt d'origine")),
                ('depot_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dépôt de destination')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('transfert', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transfert entre dépôt')),
                ('exportee', models.BooleanField(default=False, verbose_name='Exportée')),
                ('code_client', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code client')),
                ('code_depot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code dépôt')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
            ],
            options={
                'verbose_name': 'Commande Legend',
                'verbose_name_plural': 'Commandes Legend',
                'ordering': ['-date_commande', 'numero_commande'],
                'indexes': [models.Index(fields=['date_commande', 'numero_commande'], name='legend_comm_date_co_a1f7c2_idx'), models.Index(fields=['date_commande'], name='legend_comm_date_co_8f2e1a_idx'), models.Index(fields=['numero_commande'], name='legend_comm_numero__28ce1f_idx')],
                'unique_together': {('date_commande', 'numero_commande', 'depot_origine')},
            },
        ),
    ]

