# Generated by Django 6.0.1 on 2026-01-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='commandelegend',
                    new_name='legend_comm_date_co_bcdb77_idx',
                    old_name='legend_comm_date_co_a1f7c2_idx',
                ),
                migrations.RenameIndex(
                    model_name='commandelegend',
                    new_name='legend_comm_date_co_67bbfd_idx',
                    old_name='legend_comm_date_co_8f2e1a_idx',
                ),
                migrations.RenameIndex(
                    model_name='commandelegend',
                    new_name='legend_comm_numero__0cc766_idx',
                    old_name='legend_comm_numero__28ce1f_idx',
                ),
            ],
        ),
    ]
