# Generated by Django 6.0.1 on 2026-01-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRAsten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_br', models.CharField(max_length=50, verbose_name='Numéro BR')),
                ('date_br', models.DateField(verbose_name='Date BR')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
                ('code_magasin', models.ForeignKey(db_column='code_magasin', on_delete=django.db.models.deletion.PROTECT, to='core.magasin', verbose_name='Code magasin')),
            ],
            options={
                'verbose_name': 'BR Asten',
                'verbose_name_plural': 'BR Asten',
                'ordering': ['-date_br', 'numero_br'],
                'indexes': [models.Index(fields=['numero_br', 'date_br', 'code_magasin'], name='br_asten_numero__1f0c7b_idx'), models.Index(fields=['date_br'], name='br_asten_date_br_3eae0b_idx'), models.Index(fields=['code_magasin'], name='br_asten_code_ma_92a9cf_idx')],
                'unique_together': {('numero_br', 'date_br', 'code_magasin')},
            },
        ),
        migrations.CreateModel(
            name='BRIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_br', models.CharField(max_length=50, verbose_name='Numéro BR')),
                ('date_br', models.DateField(verbose_name='Date BR')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
                ('code_magasin', models.ForeignKey(db_column='code_magasin', on_delete=django.db.models.deletion.PROTECT, to='core.magasin', verbose_name='Code magasin')),
            ],
            options={
                'verbose_name': 'BR IC',
                'verbose_name_plural': 'BR IC',
                'ordering': ['-date_br', 'numero_br'],
                'indexes': [models.Index(fields=['numero_br', 'date_br', 'code_magasin'], name='br_ic_numero_br_d2aa5c_idx'), models.Index(fields=['date_br'], name='br_ic_date_br_80e3f2_idx'), models.Index(fields=['code_magasin'], name='br_ic_code_magasin_99a1e0_idx')],
                'unique_together': {('numero_br', 'date_br', 'code_magasin')},
            },
        ),
    ]







