# Generated by Django 6.0.1 on 2026-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0003_remove_bric'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brasten',
            new_name='br_brasten_numero__2a4d81_idx',
            old_name='br_asten_numero__1f0c7b_idx',
        ),
        migrations.RenameIndex(
            model_name='brasten',
            new_name='br_brasten_date_br_ec5cca_idx',
            old_name='br_asten_date_br_3eae0b_idx',
        ),
        migrations.RenameIndex(
            model_name='brasten',
            new_name='br_brasten_code_ma_f78933_idx',
            old_name='br_asten_code_ma_92a9cf_idx',
        ),
        migrations.AddField(
            model_name='brasten',
            name='avis',
            field=models.TextField(blank=True, null=True, verbose_name='Avis/Commentaire'),
        ),
    ]
