# Generated by Django 6.0.1 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0004_rename_br_asten_numero__1f0c7b_idx_br_brasten_numero__2a4d81_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brasten',
            name='commande_fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commande fournisseur'),
        ),
    ]





