# Generated by Django 6.0.1 on 2026-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0005_brasten_commande_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='brasten',
            name='date_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Date validation'),
        ),
    ]
