# Generated by Django 6.0.1 on 2026-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0006_brasten_date_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brasten',
            name='override_statut_ic',
            field=models.BooleanField(default=False, verbose_name='Statut IC modifié manuellement'),
        ),
    ]
