# Generated by Django 6.0.1 on 2026-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0008_brasten_anomalie_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRICLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_br', models.CharField(max_length=50, verbose_name='N° Réc./Ret.')),
                ('commande_fournisseur', models.CharField(max_length=100, verbose_name='N° Cde fournisseur')),
                ('date_reception', models.DateField(verbose_name='Date réception')),
                ('fichier_source', models.CharField(max_length=255, verbose_name='Fichier source')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
            ],
            options={
                'verbose_name': 'BR IC Ligne',
                'verbose_name_plural': 'BR IC Lignes',
                'ordering': ['-date_reception', 'numero_br'],
                'indexes': [models.Index(fields=['numero_br', 'commande_fournisseur', 'date_reception'], name='br_briclign_numero__71a487_idx'), models.Index(fields=['date_reception'], name='br_briclign_date_re_51af8e_idx')],
                'unique_together': {('numero_br', 'commande_fournisseur', 'date_reception')},
            },
        ),
    ]
