# Generated by Django 6.0.1 on 2026-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0009_add_bric_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRAnomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_br', models.CharField(max_length=50, verbose_name='N° BR')),
                ('code_magasin', models.CharField(max_length=20, verbose_name='Code magasin')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date réception/retour')),
                ('nom_fichier_integ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom fichier intégration')),
                ('type_mouvement', models.CharField(blank=True, max_length=10, null=True, verbose_name='Type (1=BR, 2=Retour)')),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fournisseur')),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Montant HT')),
                ('rejet_csm_entete', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rejet CSM entête')),
                ('rejet_csm_detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rejet CSM détail')),
                ('rejet_ic_entete', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rejet IC entête')),
                ('facture', models.CharField(blank=True, max_length=10, null=True, verbose_name='Facture (OUI/NON)')),
                ('fichier_source', models.CharField(max_length=255, verbose_name='Fichier source')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
            ],
            options={
                'verbose_name': 'BR Anomalie',
                'verbose_name_plural': 'BR Anomalies',
                'ordering': ['-date_reception', 'numero_br'],
                'indexes': [models.Index(fields=['numero_br', 'code_magasin'], name='br_branomal_numero__8894c8_idx'), models.Index(fields=['date_reception'], name='br_branomal_date_re_aa9c6c_idx')],
                'unique_together': {('numero_br', 'code_magasin', 'date_reception')},
            },
        ),
    ]
