# Generated by Django 6.0.1 on 2026-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0010_add_br_anomalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='brasten',
            name='numero_br_corrige',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° BR corrigé (nouveau numéro IC)'),
        ),
    ]
