# Generated by Django 6.0.1 on 2026-07-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0011_add_numero_br_corrige'),
        ('core', '0008_magasin_magasin_br'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brasten',
            index=models.Index(fields=['ic_integre'], name='br_brasten_ic_inte_bbdfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='brasten',
            index=models.Index(fields=['ic_integre', 'date_br'], name='br_brasten_ic_inte_adfa33_idx'),
        ),
        migrations.AddIndex(
            model_name='brasten',
            index=models.Index(fields=['statut_ic'], name='br_brasten_statut__036097_idx'),
        ),
    ]
