# Generated by Django 6.0.1 on 2026-01-13 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeCyrus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('numero_commande', models.CharField(max_length=50, verbose_name='Numéro de commande')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant')),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
                ('code_magasin', models.ForeignKey(db_column='code_magasin', on_delete=django.db.models.deletion.PROTECT, to='core.magasin', verbose_name='Code magasin')),
            ],
            options={
                'verbose_name': 'Commande Cyrus',
                'verbose_name_plural': 'Commandes Cyrus',
                'ordering': ['-date_commande', 'numero_commande'],
                'indexes': [models.Index(fields=['date_commande', 'numero_commande', 'code_magasin'], name='cyrus_comma_date_co_438475_idx'), models.Index(fields=['date_commande'], name='cyrus_comma_date_co_7ec53d_idx'), models.Index(fields=['code_magasin'], name='cyrus_comma_code_ma_e5de54_idx')],
                'unique_together': {('date_commande', 'numero_commande', 'code_magasin')},
            },
        ),
    ]
