# Generated by Django 6.0.1 on 2026-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyrus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandecyrus',
            name='type_commande',
            field=models.CharField(blank=True, help_text='AST ou GPV', max_length=10, null=True, verbose_name='Type commande'),
        ),
    ]
