# Generated by Django 6.0.1 on 2026-01-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyrus', '0002_commandecyrus_type_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandecyrus',
            name='type_commande',
        ),
    ]
