# Generated by Django 6.0.1 on 2026-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_full_asten_magasin'),
        ('cyrus', '0003_remove_commandecyrus_type_commande'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commandecyrus',
            index=models.Index(fields=['numero_commande'], name='cyrus_comma_numero__d4f38c_idx'),
        ),
    ]
