# Generated by Django 6.0.1 on 2026-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyrus', '0004_add_index_numero_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandecyrus',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='commandecyrus',
            name='nom_magasin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom magasin'),
        ),
        migrations.AddField(
            model_name='commandecyrus',
            name='type_commande',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type commande'),
        ),
    ]
