# Generated by Django 6.0.1 on 2026-01-18 11:17

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de ticket',
                'verbose_name_plural': 'Catégories de tickets',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SuiviTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de ticket',
                'verbose_name_plural': 'Suivis de tickets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=tickets.models.chemin_piece_jointe)),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='tickets.suiviticket')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_demande', models.CharField(choices=[('incident', 'Incident'), ('demande', 'Demande')], max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='nouveau', max_length=20)),
                ('urgence', models.CharField(choices=[('tres_basse', 'Très basse'), ('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], max_length=20)),
                ('impact', models.CharField(choices=[('tres_basse', 'Très basse'), ('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_demandes', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.magasin')),
                ('observateurs', models.ManyToManyField(blank=True, related_name='tickets_observes', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategorie')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.AddField(
            model_name='suiviticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-date_changement'],
            },
        ),
    ]
