# Generated by Django 6.0.1 on 2026-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_technicien_ticket_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigne_a',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigne_a',
            field=models.ManyToManyField(blank=True, related_name='tickets_assignes', to='tickets.technicien'),
        ),
    ]
