# Generated by Django 6.0.1 on 2026-08-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_assigne_a_ticket_assigne_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Boîte support', max_length=150)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('tenant_id', models.CharField(blank=True, max_length=200)),
                ('refresh_token', models.TextField(blank=True)),
                ('delta_link', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte email',
                'verbose_name_plural': 'Comptes email',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='cree_par_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='magasin_non_identifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='outlook_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ticket',
            name='outlook_message_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
