# Generated by Django 6.0.1 on 2026-08-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_compte_email_and_outlook_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('conversation_id', models.CharField(blank=True, max_length=500)),
                ('expediteur_email', models.EmailField(blank=True, max_length=254)),
                ('expediteur_nom', models.CharField(blank=True, max_length=200)),
                ('sujet', models.CharField(blank=True, max_length=500)),
                ('extrait', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('cree', 'Remontée créée'), ('followup', 'Suivi ajouté'), ('resolu', 'Résolution détectée'), ('ignore', 'Ignoré'), ('erreur', 'Erreur')], default='ignore', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField()),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to='tickets.compteemail')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_source', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Email reçu',
                'verbose_name_plural': 'Emails reçus',
                'ordering': ['-date_reception'],
            },
        ),
    ]
