# Generated by Django 6.0.1 on 2026-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_add_email_recu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=300, verbose_name='Gemini API Key')),
                ('gemini_model', models.CharField(blank=True, default='gemini-1.5-flash', max_length=100, verbose_name='Modèle Gemini')),
                ('polling_actif', models.BooleanField(default=False, verbose_name='Polling automatique activé')),
                ('intervalle_minutes', models.PositiveIntegerField(default=5, verbose_name='Intervalle (minutes)')),
                ('mots_cles_resolution', models.TextField(blank=True, default="résolu,resolu,réglé,regle,c'est bon,ca marche,ça marche,ok merci,merci c'est,problème résolu,tout fonctionne,nickel,fixed,resolved,done,working now", verbose_name='Mots-clés résolution (séparés par virgule)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration pipeline',
            },
        ),
    ]
