# Generated by Django 6.0.1 on 2026-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_config_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteemail',
            name='sync_depuis',
            field=models.DateField(blank=True, help_text='Ne traiter que les emails reçus après cette date', null=True),
        ),
        migrations.AlterField(
            model_name='configpipeline',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-2.5-flash', max_length=100, verbose_name='Modèle Gemini'),
        ),
    ]
