# Generated by Django 6.0.1 on 2026-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_sync_depuis'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpipeline',
            name='prompt_analyse_email',
            field=models.TextField(blank=True, verbose_name='Prompt analyse email'),
        ),
        migrations.AddField(
            model_name='configpipeline',
            name='prompt_analyse_intention',
            field=models.TextField(blank=True, verbose_name='Prompt analyse intention (suivi)'),
        ),
    ]
