# Generated by Django 6.0.1 on 2026-08-20 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_magasin_magasin_br'),
        ('tickets', '0009_add_prompts_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMagasinMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_mappings', to='core.magasin')),
            ],
            options={
                'verbose_name': 'Mapping email → magasin',
                'ordering': ['email'],
            },
        ),
    ]
