# Generated by Django 6.0.1 on 2026-08-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_email_magasin_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sujet_email',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
